/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminloginRouteImport } from './routes/adminlogin'
import { Route as AplicarRouteImport } from './routes/aplicar'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as EvaluacionesRouteImport } from './routes/evaluaciones'
import { Route as ExpedientesRouteImport } from './routes/expedientes'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as IntegracionRouteImport } from './routes/integracion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PreparacionRouteImport } from './routes/preparacion'
import { Route as EvaluacionesIdRouteImport } from './routes/evaluaciones_.$id'
import { Route as ExpedientesIdRouteImport } from './routes/expedientes_.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminloginRoute = AdminloginRouteImport.update({
  id: '/adminlogin',
  path: '/adminlogin',
  getParentRoute: () => rootRouteImport,
} as any)
const AplicarRoute = AplicarRouteImport.update({
  id: '/aplicar',
  path: '/aplicar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionesRoute = EvaluacionesRouteImport.update({
  id: '/evaluaciones',
  path: '/evaluaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesRoute = ExpedientesRouteImport.update({
  id: '/expedientes',
  path: '/expedientes',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracionRoute = IntegracionRouteImport.update({
  id: '/integracion',
  path: '/integracion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparacionRoute = PreparacionRouteImport.update({
  id: '/preparacion',
  path: '/preparacion',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionesIdRoute = EvaluacionesIdRouteImport.update({
  id: '/evaluaciones_/$id',
  path: '/evaluaciones/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIdRoute = ExpedientesIdRouteImport.update({
  id: '/expedientes_/$id',
  path: '/expedientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminlogin': typeof AdminloginRoute
  '/aplicar': typeof AplicarRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/expedientes': typeof ExpedientesRoute
  '/gracias': typeof GraciasRoute
  '/integracion': typeof IntegracionRoute
  '/login': typeof LoginRoute
  '/preparacion': typeof PreparacionRoute
  '/evaluaciones/$id': typeof EvaluacionesIdRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminlogin': typeof AdminloginRoute
  '/aplicar': typeof AplicarRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/expedientes': typeof ExpedientesRoute
  '/gracias': typeof GraciasRoute
  '/integracion': typeof IntegracionRoute
  '/login': typeof LoginRoute
  '/preparacion': typeof PreparacionRoute
  '/evaluaciones/$id': typeof EvaluacionesIdRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminlogin': typeof AdminloginRoute
  '/aplicar': typeof AplicarRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/expedientes': typeof ExpedientesRoute
  '/gracias': typeof GraciasRoute
  '/integracion': typeof IntegracionRoute
  '/login': typeof LoginRoute
  '/preparacion': typeof PreparacionRoute
  '/evaluaciones_/$id': typeof EvaluacionesIdRoute
  '/expedientes_/$id': typeof ExpedientesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminlogin'
    | '/aplicar'
    | '/diagnostico'
    | '/evaluaciones'
    | '/expedientes'
    | '/gracias'
    | '/integracion'
    | '/login'
    | '/preparacion'
    | '/evaluaciones/$id'
    | '/expedientes/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminlogin'
    | '/aplicar'
    | '/diagnostico'
    | '/evaluaciones'
    | '/expedientes'
    | '/gracias'
    | '/integracion'
    | '/login'
    | '/preparacion'
    | '/evaluaciones/$id'
    | '/expedientes/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/adminlogin'
    | '/aplicar'
    | '/diagnostico'
    | '/evaluaciones'
    | '/expedientes'
    | '/gracias'
    | '/integracion'
    | '/login'
    | '/preparacion'
    | '/evaluaciones_/$id'
    | '/expedientes_/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminloginRoute: typeof AdminloginRoute
  AplicarRoute: typeof AplicarRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EvaluacionesRoute: typeof EvaluacionesRoute
  ExpedientesRoute: typeof ExpedientesRoute
  GraciasRoute: typeof GraciasRoute
  IntegracionRoute: typeof IntegracionRoute
  LoginRoute: typeof LoginRoute
  PreparacionRoute: typeof PreparacionRoute
  EvaluacionesIdRoute: typeof EvaluacionesIdRoute
  ExpedientesIdRoute: typeof ExpedientesIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminlogin': {
      id: '/adminlogin'
      path: '/adminlogin'
      fullPath: '/adminlogin'
      preLoaderRoute: typeof AdminloginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplicar': {
      id: '/aplicar'
      path: '/aplicar'
      fullPath: '/aplicar'
      preLoaderRoute: typeof AplicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluaciones': {
      id: '/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/evaluaciones'
      preLoaderRoute: typeof EvaluacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes': {
      id: '/expedientes'
      path: '/expedientes'
      fullPath: '/expedientes'
      preLoaderRoute: typeof ExpedientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracion': {
      id: '/integracion'
      path: '/integracion'
      fullPath: '/integracion'
      preLoaderRoute: typeof IntegracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparacion': {
      id: '/preparacion'
      path: '/preparacion'
      fullPath: '/preparacion'
      preLoaderRoute: typeof PreparacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluaciones_/$id': {
      id: '/evaluaciones_/$id'
      path: '/evaluaciones/$id'
      fullPath: '/evaluaciones/$id'
      preLoaderRoute: typeof EvaluacionesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes_/$id': {
      id: '/expedientes_/$id'
      path: '/expedientes/$id'
      fullPath: '/expedientes/$id'
      preLoaderRoute: typeof ExpedientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminloginRoute: AdminloginRoute,
  AplicarRoute: AplicarRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EvaluacionesRoute: EvaluacionesRoute,
  ExpedientesRoute: ExpedientesRoute,
  GraciasRoute: GraciasRoute,
  IntegracionRoute: IntegracionRoute,
  LoginRoute: LoginRoute,
  PreparacionRoute: PreparacionRoute,
  EvaluacionesIdRoute: EvaluacionesIdRoute,
  ExpedientesIdRoute: ExpedientesIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
